spring:
  application:
    name: insurance-provider
    
server:
  port: 8081

eureka:
  client:
    service-url: 
      defaultZone: "http://localhost:8761/eureka"
  
insurance-provider-props:
   packages:
      - Silver
      - Bronze
      - Gold
      - Platinum
      - Premium

   properties:
      - Val1
      - Val2