spring:
  application:
    name: insurance-provider
    
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url: 
      defaultZone: "http://localhost:8761/eureka"
    healthcheck:
      enabled: true

  
insurance-provider-props:
   packages:
      - Silver
      - Bronze
      - Gold
      - Platinum
      - Premium

   properties:
      - Val1
      - Val2