spring:
  application:
    name: insurance-provider
    
server:
  port: 8081
  
  
insurance-provider-props:
   packages:
      - Silver
      - Bronze
      - Gold
      - Platinum

   properties:
      - Val1
      - Val2